CodeForAfrica/TwoopsTrackerUI

- src/components/Tabs/useStyles.js
This Pr implements the redesign of the account page
> [Fix] Account tabs

- src/components/Account/index.js
- src/components/Account/useStyles.js
- src/components/AccountsList/index.js
- src/components/AccountsList/useStyles.js
- src/components/ContentActions/index.js
- src/components/ListCard/index.js
- src/components/ListCard/useStyles.js
- src/components/Lists/index.js
- src/components/Lists/useStyles.js
Update Lists and List pages to match design
> [Design] Lists + List Pages

- src/components/Partners/index.js
fix Homepage partner description alignment
> [Hotfix] Partners

- src/components/InvestigationList/index.js
- src/components/InvestigationsCard/index.js
- src/pages/investigations.js
Fix investigation page redesign and pagination
> [Feature] Investigation page Redesign

- src/components/Pagination/PageSize/index.js
- src/components/Pagination/PageSize/useStyles.js
- src/components/SearchResults/index.js
- src/components/SearchResults/index.stories.js
- src/components/SearchSection/index.js
- src/components/TweetsContainer/index.js
> [Fixes] Explore page fixes

- src/components/SearchSection/index.js
> [Fix] Return Search Button

- src/components/SearchResults/index.js
Rename props passed to component to show results
> [Fix] Props Rename Fix

- .env.sample
- src/pages/api/admin/oauth/auth.js
Auth endpoint was being used instead of Callback endpoint. This of course caused logins to fail with the "Requires authentication" error message. 
N/A
> [Hotfix] Admin callback endpoint

- next.config.js
- src/components/SearchSection/index.js
- src/components/TweetsContainer/index.js
- src/lib/index.js
- src/pages/explore/index.js
- src/utils/getQueryString.js
> [Feature] Category

- src/components/UserSearchCard/index.js
This PR fixes design issues on the saved search page
> [Fix] Saved Search

- src/pages/admin/index.js
This PR fixes the import of the config.yml file for the Admin page
> [Hotfix] CMS config loading

- src/components/Hero/index.js
- src/components/SearchSection/index.js
- src/components/TweetsContainer/index.js
If saved query contains query/keyword, ensure it's loaded into the search field.
> [Fix] Show saved query on load

- src/theme/index.js
Update lg screen size to 1440px.
> [Chore] Theme update

- src/components/Chart/LineScope.js
- src/components/Chart/index.js
- src/components/Chart/index.stories.js
- src/components/ExploreTool/index.js
- src/components/Filter/useStyles.js
- src/components/Footer/useStyles.js
- src/components/Hero/index.js
- src/components/InvestigationsCard/useStyles.js
- src/components/InvestigationsPreview/index.js
- src/components/LoginForm/useStyles.js
- src/components/LoginMenu/index.js
- src/components/Menu/index.js
- src/components/Navigation/index.js
- src/components/Partners/index.js
- src/components/Search/useStyles.js
- src/components/SearchSection/index.js
- src/components/Tabs/index.js
- src/components/Tabs/useStyles.js
- src/components/TweetCard/useStyles.js
- src/components/TweetsContainer/index.js
- src/components/TweetsContainer/useStyles.js
- src/components/UserProfile/index.js
- src/components/UserSearchCard/index.js
- src/theme/index.js
- Update theme typographies
- Update all `breakpoints.up("xl")` to `breakpoints.up("lg")` and solve related fixes
- [Update Navigation](https://www.pivotaltracker.com/story/show/180944203)
- [Update Charts](https://www.pivotaltracker.com/story/show/180961696)
- [Fix Watchlist Chart](https://www.pivotaltracker.com/story/show/180934347)
> [Chore] Update charts & navigation

- src/components/SearchSection/index.js
- src/lib/index.js
Add search search support for tweet older than 30 days
> [Chore]Add support for tweets older than 30 days

- src/components/Account/index.js
- src/components/Account/useStyles.js
- src/components/AccountsList/index.js
- src/components/AccountsList/useStyles.js
- src/components/ListModal/index.js
- src/components/ListModal/useStyles.js
- src/pages/account/lists/[listId].js
Issues Fixed:
- Delete button not showing on list accounts. Link to [Pivotal](https://www.pivotaltracker.com/story/show/180935378)
- Delete button spacing in Modal. Link to [Pivotal](https://www.pivotaltracker.com/story/show/180958750)
- Adjust twitter image icon size as per design.
> [Fix] Account Delete

- src/components/Card/Media.js
- src/components/Card/index.js
- src/components/InvestigationList/index.js
- src/components/InvestigationList/useStyles.js
- src/components/InvestigationsCard/index.js
- src/components/InvestigationsCard/useStyles.js
> [Fix] Investigate Card

- src/components/TweetCard/index.js
- src/components/TweetCard/useStyles.js
Fix `See More` button affordance.
> [Fix] See More button affordance

- .github/workflows/codeql-analysis.yml
> Create CodeQL Analysis

- src/components/Filter/index.js
- src/components/Filter/useStyles.js
- src/components/SearchResults/index.js
- src/components/SearchSection/index.js
- src/components/TweetsContainer/index.js
- src/lib/index.js
- src/pages/explore/index.js
- src/utils/getQueryString.js
- The filters are supposed to be the same height as the search bar and on the same line. 
- The labels on the filters hide when using it but then turn red when closed. They should remain black.
> [Fix] Search Section Layout + Design Changes

- src/components/ListModal/index.js
- src/components/ListModal/useStyles.js
- src/components/Lists/index.js
Add support for errors in create list account
> Create list loader

- src/components/Card/Content.js
- src/components/Card/useStyles.js
- src/components/InvestigationList/index.js
- src/components/InvestigationList/useStyles.js
- src/components/InvestigationsCard/index.js
- src/components/InvestigationsCard/useStyles.js
- src/components/TweetCard/index.js
- src/components/TweetsContainer/index.js
This PR fixes the way Card is used to implement /investigations page to closely match the designs.
> [Fix] Investigations Page

- src/components/ContentActions/index.js
Ensure label and buttons have same padding (0) for better alignment.
> [Fix] Download Label and File Type Alignment

- content/components/accountList.md
> [Fix] Missing Delete Label

- public/template.csv
- src/components/Upload/index.js
All public accounts have evidence
> [Fix] Fix CSV file evidence error

- src/components/Chart/LineScope.js
- src/components/Chart/index.js
- Update chart scope to render md screen charts per design
reaking change which fixes an issue)
> [Fix] Chart on md screen

- content/components/search.md
- src/components/Account/index.js
- src/components/AccountsList/index.js
- src/components/Lists/index.js
- src/components/LoginMenu/index.js
- src/components/Navigation/DesktopNavigation/index.js
- src/components/Pagination/index.stories.js
- src/components/Partners/index.js
- src/components/SearchSection/index.js
- src/config/index.js
- src/lib/index.js
- src/pages/account/lists/[listId].js
- src/pages/api/accounts.js
- src/pages/explore/accounts.js
- src/pages/explore/index.js
- src/pages/investigations.js
- src/utils/getQueryString.js
> [Fix] Feedback 2

- src/components/UserAccount/index.js
- src/pages/api/user/index.js
Delete user account from TwoopsTracker when requested (Depends on https://github.com/CodeForAfrica/TwoopsTracker/pull/58)
N/A
> [Feat] Delete user account

- src/components/UpdateProfile/index.js
> [HotFix] Account Type Check

- contrib/dokku/Dockerfile
- package.json
- src/components/Upload/index.js
- src/lib/index.js
- src/pages/api/lists/upload.js
Fix CSV upload by sending the CSV from the uploads NextJs endpoint.
> Chore fix CSV upload

- content/pages/account/update.md
- package.json
- src/components/Chart/index.js
- yarn.lock
We're currently using outdated node v16. This PR:
N/A
> Fix outdated build

- .github/workflows/main.yml
- Dockerfile
- package.json
Github Actions are currently failing due to an overdue [breaking change](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)
> Upgrade actions version
